name: Windows App

on: [workflow_dispatch]

env:
  PYVER: "3.12"
  QT_API: "pyqt6"

jobs:
  winapp:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "${{ env.PYVER }}" }
      - run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade -e .[${{ env.QT_API }},pygments]
          python -m pip install --upgrade pyinstaller pillow
      - name: Create ICO file
        run: |
          mkdir -p gitfourchette/assets/icons
          python -c "from PIL import Image; img = Image.open('gitfourchette/assets/icons/gitfourchette.png'); img.save('gitfourchette/assets/icons/gitfourchette.ico')"
      - name: Build Windows executable
        run: |
          cmd /c pkg\pyinstaller\build-windows-exe.bat
      - name: Create ZIP archive
        run: |
          7z a -tzip GitFourchette-win.zip ./dist/GitFourchette.exe
      - uses: actions/upload-artifact@v4
        with: { name: win-app, path: GitFourchette-win.zip, compression-level: 0 } 